services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:8080

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
      - OLLAMA_TIMEOUT=900s
      - OLLAMA_KEEP_ALIVE=15m
      - OLLAMA_NUM_THREAD=2
      - OLLAMA_CONTEXT_LENGTH=2048
      - OLLAMA_BATCH_SIZE=256
      - OLLAMA_DEBUG=1
      - OLLAMA_GPU_LAYERS=0
    deploy:
      resources:
        limits:
          memory: 6G
    entrypoint: >
      /bin/sh -c "
      ollama serve &
      sleep 5 &&
      ollama pull tinyllama &&
      wait
      "

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=skyvern
      - POSTGRES_PASSWORD=skyvern
      - POSTGRES_DB=skyvern
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U skyvern"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  skyvern:
    container_name: skyvern
    image: public.ecr.aws/skyvern/skyvern:latest
    restart: on-failure
    ports:
      - 8000:8000
      - 9222:9222 # for cdp browser forwarding
    volumes:
      - ./.artifacts:/data/artifacts
      - ./.videos:/data/videos
      - ./.har:/data/har
      - ./.log:/data/log
      - ./.streamlit:/app/.streamlit
    environment:
      - DATABASE_STRING=postgresql+psycopg://skyvern:skyvern@postgres:5432/skyvern
      - BROWSER_TYPE=chromium-headful
      - ENABLE_CODE_BLOCK=true
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - LOG_LEVEL=debug
      - ENABLE_CSS_SHAPE_CONVERT=false
      # Ollama Support:
      - LLM_KEY=OLLAMA
      - ENABLE_OLLAMA=true
      - OLLAMA_MODEL=tinyllama
      - OLLAMA_SERVER_URL=http://ollama:11434
      - OLLAMA_FORMAT=json
      - OLLAMA_TEMPERATURE=0.1
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "test", "-f", "/app/.streamlit/secrets.toml"]
      interval: 5s
      timeout: 5s
      retries: 5

  skyvern-ui:
    container_name: skyvern-ui
    image: public.ecr.aws/skyvern/skyvern-ui:latest
    restart: on-failure
    ports:
      - 8080:8080
      - 9090:9090
    volumes:
      - ./.artifacts:/data/artifacts
      - ./.videos:/data/videos
      - ./.har:/data/har
      - ./.streamlit:/app/.streamlit
    environment:
      - VITE_ENABLE_CODE_BLOCK=true
      - VITE_WSS_BASE_URL=ws://localhost:8000/api/v1
      - VITE_API_BASE_URL=http://localhost:8000/api/v1
      - VITE_SKYVERN_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQ4OTMyMjU3MjgsInN1YiI6Im9fMzk3NjM4OTMwNjcwMDI5MTE0In0.0PYAaPzI92uxXgF2h_x-ii5v64FUQ6RvH-LKNPImm_U
    depends_on:
      skyvern:
        condition: service_healthy

volumes:
  ollama:
  pgdata: